### ISSUE TITLE
scheduleRate.startsWith is not a function

### ISSUE THREAD

**Issue by kanil4** [Meemaw/serverless-offline-schedule#16]
I am getting the error: `scheduleRate.startsWith is not a function` while using the plugin. I am using version `1.0.4` with serverless version `2.53.0`.

Here is how my schedule looks like:
`events:
      - schedule:
          description: "Test"
          rate: "rate(2 minutes)"
          enabled: true
`
I did try logging where the error appeard to come form and i see:

Scheduled Event:  [ 'rate(2 minutes)' ]

It seems to be an Array and `.startsWith` fails as its not a string in function: `exports.convertExpressionToCron`

**Comment by diego09310** [comment]
Hi, I'm having the same issue. I've tried with different formats and I'm having this issue or something related. 

It can be reproduced using the example [aws-node-scheduled-cron](https://github.com/serverless/examples/tree/master/aws-node-scheduled-cron) and adding this plugin (I also added the serverless-offline plugin).

I've been looking into it, and during the plugins initialization the `functions` object is parsed properly, but then, when the plugin is actually used that part of the object has changed.

**Comment by zacharykapank** [comment]
Experienced the same issue on v1.0.4, formatting the schedule like below fixed it for me. 

``` 
events:
  - schedule: 
      rate: rate(2 minutes)
```

**Comment by MichaelCharles** [comment]
Also having this issue on 1.0.4

**Comment by MichaelCharles** [comment]
I made a pull request ( #25  ) which solves the problem for me locally.

**Comment by eliakaris** [comment]
Does anyone have a desire to publish the latest changes to NPM?  The rate as an array change makes this broken.

**Comment by dtsuper3** [comment]
@Meemaw  can you please create a new release for this change in the NPM package?

**Comment by mir1198yusuf** [comment]
@Meemaw facing same issue .
package.json has `"serverless-offline-schedule": "^1.0.4"`
serverless.yaml has below format
```
events:
      - schedule: 
          rate: rate(5 minutes)
```
